import React,{useEffect,useRef,useState} from 'react';
const api=window.nexumons;
function Icon({name,...props}){const paths={arrow:<><path d="M4 12h15M13 5l7 7-7 7"/></>,close:<><path d="m6 6 12 12M6 18 18 6"/></>,minus:<path d="M5 12h14"/>,settings:<><path d="M4 6h16M4 12h16M4 18h16"/><circle cx="9" cy="6" r="2"/><circle cx="15" cy="12" r="2"/><circle cx="8" cy="18" r="2"/></>,compass:<><circle cx="12" cy="12" r="9"/><path d="m16 8-3 5-5 3 3-5z"/></>,logout:<><path d="M10 4H4v16h6M9 12h11m-4-4 4 4-4 4"/></>};return <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}>{paths[name]||paths.arrow}</svg>}
const chapters=[['01','Ton premier refuge','Reçois ton starter, découvre ton île et apprends à récolter, miner et capturer.'],['02','Une île qui grandit','Enchaîne les quêtes pour agrandir ta base, améliorer ta mine et développer tes habitats.'],['03','Au-delà des nuages','Pars en expédition vers de nouvelles îles. Les défis et les chapitres ouvrent les destinations suivantes.']];
export default function App(){
 const [profile,setProfile]=useState(null),[name,setName]=useState(''),[ram,setRam]=useState(4),[server,setServer]=useState(''),[maxRam,setMaxRam]=useState(12),[busy,setBusy]=useState(false),[msBusy,setMsBusy]=useState(false),[status,setStatus]=useState(null),[error,setError]=useState(''),[tab,setTab]=useState('home'),[settings,setSettings]=useState(false);const auth=useRef(null);
 useEffect(()=>{if(!api){setError('Ouvre cette interface depuis le launcher Nexumons Skyblock.');return;}
 Promise.all([api.getSettings(),api.getSystemInfo()]).then(([s,i])=>{setName(s.lastUsername||'');setServer(s.serverAddress||'');setMaxRam(i.maxRam||12);setRam(Math.min(s.ram||4,i.maxRam||12));}).catch(()=>setError('Impossible de lire les réglages.'));
 return api.onStatus(s=>{setStatus(s);if(['closed','launched','error'].includes(s.stage))setBusy(false);});},[]);
 async function login(microsoft){setError('');setMsBusy(true);try{const r=await(microsoft?api.loginMicrosoft():api.loginOffline(name.trim()));if(!r.ok)throw Error(r.error);auth.current=r.auth;setProfile(r.profile);if(!microsoft)await api.saveSettings({lastUsername:name.trim()});}catch(e){setError(e.message);}finally{setMsBusy(false);}}
 async function play(){setError('');if(!auth.current){setError('Connecte ton compte pour commencer.');return;}if(server&&!/^[a-zA-Z0-9.\-]+(:[0-9]{1,5})?$/.test(server.trim())){setSettings(true);setError('Adresse du serveur invalide.');return;}setBusy(true);try{await api.saveSettings({ram,serverAddress:server.trim()});const r=await api.launch({auth:auth.current,ram});if(!r.ok)throw Error(r.error);}catch(e){setError(e.message);setBusy(false);}}
 function logout(){auth.current=null;setProfile(null);setStatus(null);setError('');}
 return <div className="app">
 <header className="topbar"><a href="#main" className="skip">Aller au contenu</a><div className="brand"><span className="brand-mark"><Icon name="compass"/></span><span>NEXUMONS<small>SKYBLOCK</small></span></div><nav aria-label="Navigation"><button className={tab==='home'?'selected':''} onClick={()=>setTab('home')}>Le refuge</button><button className={tab==='journey'?'selected':''} onClick={()=>setTab('journey')}>L’aventure</button><button onClick={()=>api.openExternal('https://discord.gg/tE8GwZbz7h')}>Communauté <span>↗</span></button></nav><div className="window-actions"><button aria-label="Réduire" onClick={()=>api.minimize()}><Icon name="minus"/></button><button aria-label="Fermer" onClick={()=>api.close()}><Icon name="close"/></button></div></header>
 <main id="main" className="landscape"><div className="island-art" role="img" aria-label="Une île flottante avec une maison, des cultures et une cascade au-dessus des nuages"/><div className="shade"/>
 {tab==='home'?<section className="welcome"><p className="eyebrow"><span/>Un nouveau départ, au-dessus des nuages</p><h1>Un petit bout<br/>de ciel.<em>Tout à construire.</em></h1><p className="intro">Une île à faire grandir. Des Pokémon à rencontrer.<br/>Une aventure qui se débloque, quête après quête.</p><div className="features"><span>500 quêtes</span><span>Habitats vivants</span><span>Expéditions</span></div><button className="discover" onClick={()=>setTab('journey')}>Découvrir l’aventure <Icon name="arrow"/></button></section>:<section className="journey"><p className="eyebrow">Le carnet d’un explorateur</p><h1>Chaque quête<br/>ouvre l’horizon.</h1><div className="chapter-list">{chapters.map(([n,title,text])=><article key={n}><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></article>)}</div><button className="discover" onClick={()=>setTab('home')}>← Revenir au refuge</button></section>}
 <div className="map-note"><Icon name="compass"/><span>TON ÎLE.<br/><b>TON HISTOIRE.</b></span></div>
 {settings&&<aside className="settings" aria-label="Réglages du jeu"><div className="settings-title"><h2>Préparer le voyage</h2><button aria-label="Fermer les réglages" onClick={()=>setSettings(false)}><Icon name="close"/></button></div><label htmlFor="server">Adresse du serveur</label><input id="server" value={server} placeholder="127.0.0.1:25598" onChange={e=>setServer(e.target.value)} disabled={busy}/><p className="help">Le pack actuel rejoint le test Skyblock. Depuis un autre ordinateur, utilise l’adresse d’un serveur accessible sur le réseau.</p><label htmlFor="memory">Mémoire du jeu <b>{ram} Go</b></label><input id="memory" type="range" min="2" max={maxRam} value={ram} onChange={e=>setRam(Number(e.target.value))} disabled={busy}/><p className="help">4 Go par défaut. Ajuste selon la mémoire disponible.</p><button className="save" disabled={busy} onClick={async()=>{if(server&&!/^[a-zA-Z0-9.\-]+(:[0-9]{1,5})?$/.test(server.trim())){setError('Adresse du serveur invalide.');return;}await api.saveSettings({ram,serverAddress:server.trim()});setSettings(false);}}>Enregistrer</button></aside>}
 </main>
 <footer className="dock"><div className="dock-top"><span className="channel"><i/>SKYBLOCK · VERSION DE TEST</span><button className="tune" onClick={()=>setSettings(!settings)}><Icon name="settings"/>Réglages</button></div>
 {profile?<div className="launch-row"><div className="account"><span className="avatar">{profile.name.slice(0,2).toUpperCase()}</span><div><b>{profile.name}</b><small>{profile.type==='premium'?'Compte Microsoft connecté':'Session de test locale'}</small></div><button className="logout" onClick={logout} disabled={busy} aria-label="Déconnexion"><Icon name="logout"/></button></div><div className="launch-details"><b>Le ciel t’attend.</b><small>Le pack sera vérifié avant le départ.</small></div><button className="primary" disabled={busy} onClick={play}>{busy?<span className="spinner"/>:null}{busy?'Préparation…':'Rejoindre mon île'}{!busy&&<Icon name="arrow"/>}</button></div>:<div className="launch-row"><div className="login-copy"><b>Prêt à poser la première pierre ?</b><small>Connecte ton compte pour embarquer.</small></div><button className="primary microsoft" disabled={msBusy||!api} onClick={()=>login(true)}><span className="ms-logo"><i/><i/><i/><i/></span>{msBusy?'Connexion…':'Connexion Microsoft'}</button><details className="local"><summary>Test local</summary><div><label htmlFor="pseudo">Pseudo de test</label><input id="pseudo" maxLength="16" value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&name.trim().length>=3&&!msBusy&&login(false)}/><button disabled={msBusy||name.trim().length<3} onClick={()=>login(false)}>Continuer</button></div></details></div>}
 {status&&<div className="progress" role="status"><div className="track"><span style={{width:Math.max(0,Math.min(100,status.percent||0))+'%'}}/></div><p>{status.text}</p></div>}{error&&<p className="error" role="alert">{error}</p>}
 </footer></div>;
}
