import React,{useEffect,useRef,useState} from 'react';
const api=window.nexumons;
function Icon({name,...props}){const paths={arrow:<><path d="M4 12h15M13 5l7 7-7 7"/></>,close:<><path d="m6 6 12 12M6 18 18 6"/></>,minus:<path d="M5 12h14"/>,settings:<><path d="M4 6h16M4 12h16M4 18h16"/><circle cx="9" cy="6" r="2"/><circle cx="15" cy="12" r="2"/><circle cx="8" cy="18" r="2"/></>,compass:<><circle cx="12" cy="12" r="9"/><path d="m16 8-3 5-5 3 3-5z"/></>,logout:<><path d="M10 4H4v16h6M9 12h11m-4-4 4 4-4 4"/></>};return <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}>{paths[name]||paths.arrow}</svg>}
const chapters=[['01','Ton premier refuge','Reçois ton starter, découvre ton île et apprends à récolter, miner et capturer.'],['02','Une île qui grandit','Enchaîne les quêtes pour agrandir ta base, améliorer ta mine et développer tes habitats.'],['03','Au-delà des nuages','Pars en expédition vers de nouvelles îles. Les défis et les chapitres ouvrent les destinations suivantes.']];
export default function App(){
 const [online,setOnline]=useState(null),[profile,setProfile]=useState(null),[name,setName]=useState(''),[ram,setRam]=useState(4),[server,setServer]=useState(''),[maxRam,setMaxRam]=useState(12),[busy,setBusy]=useState(false),[msBusy,setMsBusy]=useState(false),[status,setStatus]=useState(null),[error,setError]=useState(''),[tab,setTab]=useState('home'),[settings,setSettings]=useState(false);const auth=useRef(null);
 useEffect(()=>{if(!api){setError('Ouvre cette interface depuis le launcher Cobbloria.');return;}
 Promise.all([api.getSettings(),api.getSystemInfo()]).then(([s,i])=>{setName(s.lastUsername||'');setServer('172.241.3.147:25585');setMaxRam(i.maxRam||12);setRam(Math.min(s.ram||4,i.maxRam||12));}).catch(()=>setError('Impossible de lire les réglages.'));
 return api.onStatus(s=>{setStatus(s);if(['closed','launched','error'].includes(s.stage))setBusy(false);});},[]);
 useEffect(()=>{if(!api?.getServerStatus)return;let active=true;const refresh=()=>api.getServerStatus().then(s=>{if(active)setOnline(s);}).catch(()=>{if(active)setOnline({online:false,players:[]});});refresh();const timer=setInterval(refresh,30000);return()=>{active=false;clearInterval(timer);};},[]);
 async function login(microsoft){setError('');setMsBusy(true);try{const r=await(microsoft?api.loginMicrosoft():api.loginOffline(name.trim()));if(!r.ok)throw Error(r.error);auth.current=r.auth;setProfile(r.profile);if(!microsoft)await api.saveSettings({lastUsername:name.trim()});}catch(e){setError(e.message);}finally{setMsBusy(false);}}
 async function play(){setError('');if(!auth.current){setError('Connecte ton compte pour commencer.');return;}if(server&&!/^[a-zA-Z0-9.\-]+(:[0-9]{1,5})?$/.test(server.trim())){setSettings(true);setError('Adresse du serveur invalide.');return;}setBusy(true);try{await api.saveSettings({ram,serverAddress:server.trim()});const r=await api.launch({auth:auth.current,ram});if(!r.ok)throw Error(r.error);}catch(e){setError(e.message);setBusy(false);}}
 function logout(){auth.current=null;setProfile(null);setStatus(null);setError('');}
 return <div className="app">
 <header className="topbar"><a href="#main" className="skip">Aller au contenu</a><div className="brand"><span className="brand-mark"><Icon name="compass"/></span><span>COBBLORIA<small>SKYBLOCK</small></span></div><nav aria-label="Navigation"><button className={tab==='home'?'selected':''} onClick={()=>setTab('home')}>Le refuge</button><button className={tab==='journey'?'selected':''} onClick={()=>setTab('journey')}>L’aventure</button><button onClick={()=>api.openExternal('https://discord.gg/tE8GwZbz7h')}>Communauté <span>↗</span></button></nav><div className="window-actions"><button aria-label="Réduire" onClick={()=>api.minimize()}><Icon name="minus"/></button><button aria-label="Fermer" onClick={()=>api.close()}><Icon name="close"/></button></div></header>
 <main id="main" className="landscape"><div className="island-art" role="img" aria-label="Une île flottante avec une maison, des cultures et une cascade au-dessus des nuages"/><div className="shade"/>
 {tab==='home'?<section className="welcome"><p className="eyebrow"><span/>Un nouveau départ, au-dessus des nuages</p><h1>Un petit bout<br/>de ciel.<em>Tout à construire.</em></h1><p className="intro">Une île à faire grandir. Des Pokémon à rencontrer.<br/>Une aventure qui se débloque, quête après quête.</p><div className="features"><span>500 quêtes</span><span>Habitats vivants</span><span>Expéditions</span></div><button className="discover" onClick={()=>setTab('journey')}>Découvrir l’aventure <Icon name="arrow"/></button></section>:<section className="journey"><p className="eyebrow">Le carnet d’un explorateur</p><h1>Chaque quête<br/>ouvre l’horizon.</h1><div className="chapter-list">{chapters.map(([n,title,text])=><article key={n}><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></article>)}</div><button className="discover" onClick={()=>setTab('home')}>← Revenir au refuge</button></section>}
 <aside className="online-panel" aria-label="Joueurs connectés"><div className="online-heading"><span className={online?.online?"live-dot":"live-dot offline"}/><h2>{online===null?"Recherche du serveur…":online.online?"Le refuge est ouvert":"Serveur indisponible"}</h2><b>{online?.online?`${online.count} / ${online.max}`:"—"}</b></div><p>{online?.online?(online.count?"Les explorateurs en ligne":"Le ciel est calme. À toi de jouer."):"La liste se rafraîchit automatiquement."}</p><div className="online-players">{online?.players?.map(p=><div className="online-player" key={p.name}><img src={`https://mc-heads.net/avatar/${p.uuid||encodeURIComponent(p.name)}/32`} alt="" width="28" height="28" onError={e=>{e.currentTarget.style.display="none";}}/><span>{p.name}</span></div>)}</div>{online?.online&&online.count>(online.players?.length||0)&&<small>+ {online.count-(online.players?.length||0)} joueurs · liste partielle fournie par le serveur</small>}</aside><div className="map-note"><Icon name="compass"/><span>TON ÎLE.<br/><b>TON HISTOIRE.</b></span></div>
 {settings&&<aside className="settings" aria-label="Réglages du jeu"><div className="settings-title"><h2>Préparer le voyage</h2><button aria-label="Fermer les réglages" onClick={()=>setSettings(false)}><Icon name="close"/></button></div><p className="help">Connexion automatique au Cobbloria.<br/>172.241.3.147:25585</p><label htmlFor="memory">Mémoire du jeu <b>{ram} Go</b></label><input id="memory" type="range" min="2" max={maxRam} value={ram} onChange={e=>setRam(Number(e.target.value))} disabled={busy}/><p className="help">4 Go par défaut. Ajuste selon la mémoire disponible.</p><button className="save" disabled={busy} onClick={async()=>{if(server&&!/^[a-zA-Z0-9.\-]+(:[0-9]{1,5})?$/.test(server.trim())){setError('Adresse du serveur invalide.');return;}await api.saveSettings({ram,serverAddress:server.trim()});setSettings(false);}}>Enregistrer</button></aside>}
 </main>
 <footer className="dock"><div className="dock-top"><span className="channel"><i/>SKYBLOCK · SERVEUR JOUEURS</span><button className="tune" onClick={()=>setSettings(!settings)}><Icon name="settings"/>Réglages</button></div>
 {profile?<div className="launch-row"><div className="account"><span className="avatar">{profile.name.slice(0,2).toUpperCase()}</span><div><b>{profile.name}</b><small>{profile.type==='premium'?'Compte Microsoft connecté':'Pseudo hors ligne'}</small></div><button className="logout" onClick={logout} disabled={busy} aria-label="Déconnexion"><Icon name="logout"/></button></div><div className="launch-details"><b>Le ciel t’attend.</b><small>Le pack sera vérifié avant le départ.</small></div><button className="primary" disabled={busy} onClick={play}>{busy?<span className="spinner"/>:null}{busy?'Préparation…':'Rejoindre mon île'}{!busy&&<Icon name="arrow"/>}</button></div>:<div className="launch-row"><div className="login-copy"><b>Prêt à poser la première pierre ?</b><small>Connecte ton compte pour embarquer.</small></div><button className="primary microsoft" disabled={msBusy||!api} onClick={()=>login(true)}><span className="ms-logo"><i/><i/><i/><i/></span>{msBusy?'Connexion…':'Connexion Microsoft'}</button><details className="local"><summary>Jouer avec un pseudo</summary><div><label htmlFor="offline-name">Ton pseudo Minecraft</label><input id="offline-name" value={name} maxLength="16" autoComplete="username" placeholder="Ex. Explorateur" onChange={e=>setName(e.target.value)} disabled={msBusy}/><p>Inscription et mot de passe demandés sur le serveur. Les pseudos Microsoft restent réservés à leurs propriétaires.</p><button disabled={msBusy||!api||!/^[A-Za-z0-9_]{3,16}$/.test(name.trim())} onClick={()=>login(false)}>Continuer avec ce pseudo</button></div></details></div>}
 {status&&<div className="progress" role="status"><div className="track"><span style={{width:Math.max(0,Math.min(100,status.percent||0))+'%'}}/></div><p>{status.text}</p></div>}{error&&<p className="error" role="alert">{error}</p>}
 </footer></div>;
}
